
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    #region The Tables

    private item.TbItem m_TbItem;
    public item.TbItem TbItem 
    {
        get
        {
            if (m_TbItem == null)
            {
                m_TbItem = new item.TbItem(defaultLoader("item_tbitem"));
                m_TbItem.ResolveRef(this);
            }
            return m_TbItem;
        }
        set
        {
            m_TbItem = value;
            m_TbItem.ResolveRef(this);
        }
    }
    private Tbitem2 m_Tbitem2;
    public Tbitem2 Tbitem2 
    {
        get
        {
            if (m_Tbitem2 == null)
            {
                m_Tbitem2 = new Tbitem2(defaultLoader("tbitem2"));
                m_Tbitem2.ResolveRef(this);
            }
            return m_Tbitem2;
        }
        set
        {
            m_Tbitem2 = value;
            m_Tbitem2.ResolveRef(this);
        }
    }
    private l10n.Tbtextinfo m_Tbtextinfo;
    public l10n.Tbtextinfo Tbtextinfo 
    {
        get
        {
            if (m_Tbtextinfo == null)
            {
                m_Tbtextinfo = new l10n.Tbtextinfo(defaultLoader("l10n_tbtextinfo"));
                m_Tbtextinfo.ResolveRef(this);
            }
            return m_Tbtextinfo;
        }
        set
        {
            m_Tbtextinfo = value;
            m_Tbtextinfo.ResolveRef(this);
        }
    }

    #endregion

    System.Func<string, ByteBuf> defaultLoader;

    public Tables(System.Func<string, ByteBuf> loader)
    {
        SetDefaultLoader(loader);
        Init();
    }
    
    public void SetDefaultLoader(System.Func<string, ByteBuf> loader)
    {
        defaultLoader = null;
        defaultLoader = loader;
    }

    //public partial void Init();

    public void Init(){}
}

}
