
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.l10n
{
public partial class Tblocalization
{
    private readonly System.Collections.Generic.Dictionary<string, l10n.localization> _dataMap;
    private readonly System.Collections.Generic.List<l10n.localization> _dataList;
    
    public Tblocalization(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, l10n.localization>();
        _dataList = new System.Collections.Generic.List<l10n.localization>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            l10n.localization _v;
            _v = l10n.localization.Deserializelocalization(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, l10n.localization> DataMap => _dataMap;
    public System.Collections.Generic.List<l10n.localization> DataList => _dataList;

    public l10n.localization GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public l10n.localization Get(string key) => _dataMap[key];
    public l10n.localization this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

