
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.l10n
{
public partial class Tbtextinfo
{
    private readonly System.Collections.Generic.Dictionary<string, l10n.textinfo> _dataMap;
    private readonly System.Collections.Generic.List<l10n.textinfo> _dataList;
    
    public Tbtextinfo(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, l10n.textinfo>();
        _dataList = new System.Collections.Generic.List<l10n.textinfo>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            l10n.textinfo _v;
            _v = l10n.textinfo.Deserializetextinfo(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, l10n.textinfo> DataMap => _dataMap;
    public System.Collections.Generic.List<l10n.textinfo> DataList => _dataList;

    public l10n.textinfo GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public l10n.textinfo Get(string key) => _dataMap[key];
    public l10n.textinfo this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

